# Generated by Django 4.2.5 on 2023-10-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemAmmunition',
        ),
        migrations.DeleteModel(
            name='ItemArmour',
        ),
        migrations.DeleteModel(
            name='ItemOther',
        ),
        migrations.DeleteModel(
            name='ItemWeapon',
        ),
        migrations.AddField(
            model_name='item',
            name='ap',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='carries',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='encumbrance',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_2h',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='locations',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='penalty',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='qualities_and_flaws',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='range',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
