# Generated by Django 4.2.5 on 2023-10-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_itemammunition_delete_itemarmour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityFlaw',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('group', models.CharField(max_length=256, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
