# Generated by Django 4.2.5 on 2023-10-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_qualityflaw_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='qualityflaw',
            name='description',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
