# Generated by Django 4.2.5 on 2023-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_description_alter_qualityflaw_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityflaw',
            name='quality_or_flaw',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
