# Generated by Django 4.2.5 on 2023-10-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAmmunition',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('damage', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('range', models.CharField(max_length=200, null=True)),
                ('qualities_and_flaws', models.CharField(max_length=200, null=True)),
            ],
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='ItemArmour',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('locations', models.CharField(max_length=200, null=True)),
                ('penalty', models.CharField(max_length=200, null=True)),
                ('ap', models.CharField(max_length=200, null=True)),
                ('qualities_and_flaws', models.CharField(max_length=200, null=True)),
            ],
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='ItemOther',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('carries', models.CharField(max_length=200, null=True)),
            ],
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='ItemWeapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('type', models.CharField(max_length=200, null=True)),
                ('damage', models.CharField(max_length=200, null=True)),
                ('is_2h', models.BooleanField(null=True)),
                ('range', models.CharField(max_length=200, null=True)),
                ('qualities_and_flaws', models.CharField(max_length=200, null=True)),
            ],
            bases=('main.item',),
        ),
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='encumbrance',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
