# Generated by Django 4.2.5 on 2023-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_qualityflaw_quality_or_flaw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('class_name', models.CharField(null=True)),
                ('limitations', models.CharField(null=True)),
                ('summary', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
                ('advance_scheme', models.CharField(null=True)),
                ('career_path', models.CharField(null=True)),
                ('quotations', models.CharField(null=True)),
                ('adventuring', models.CharField(null=True)),
                ('source', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('status', models.CharField(null=True)),
                ('skills', models.CharField(null=True)),
                ('talents', models.CharField(null=True)),
                ('trappings', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
                ('trappings', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
                ('opinions', models.CharField(null=True)),
                ('source', models.CharField(null=True)),
                ('weapon_skill', models.CharField(null=True)),
                ('ballistic_skill', models.CharField(null=True)),
                ('strength', models.CharField(null=True)),
                ('toughness', models.CharField(null=True)),
                ('agility', models.CharField(null=True)),
                ('dexterity', models.CharField(null=True)),
                ('intelligence', models.CharField(null=True)),
                ('willpower', models.CharField(null=True)),
                ('fellowship', models.CharField(null=True)),
                ('wounds', models.CharField(null=True)),
                ('fate_points', models.CharField(null=True)),
                ('resilience', models.CharField(null=True)),
                ('extra_points', models.CharField(null=True)),
                ('movement', models.CharField(null=True)),
                ('skills', models.CharField(null=True)),
                ('talents', models.CharField(null=True)),
                ('forenames', models.CharField(default=None, null=True)),
                ('surnames', models.CharField(default=None, null=True)),
                ('clans', models.CharField(default=None, null=True)),
                ('epithets', models.CharField(default=None, null=True)),
                ('age', models.CharField(default=None, null=True)),
                ('eye_colour', models.CharField(default=None, null=True)),
                ('hair_colour', models.CharField(default=None, null=True)),
                ('height', models.CharField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('attribute', models.CharField(null=True)),
                ('basic_advance', models.CharField(null=True)),
                ('grouped', models.BooleanField(null=True)),
                ('description', models.CharField(null=True)),
                ('specialization', models.CharField(default=None, null=True)),
                ('source', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(null=True)),
                ('max', models.CharField(null=True)),
                ('tests', models.CharField(default=None, null=True)),
                ('description', models.CharField(null=True)),
                ('source', models.CharField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='ap',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='carries',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='encumbrance',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='locations',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='penalty',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='qualities_and_flaws',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='range',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='qualityflaw',
            name='description',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='qualityflaw',
            name='group',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='qualityflaw',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualityflaw',
            name='name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='qualityflaw',
            name='quality_or_flaw',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='qualityflaw',
            name='source',
            field=models.CharField(null=True),
        ),
    ]
