# Generated by Django 4.2.5 on 2023-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemother',
            name='qualities_and_flaws',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
