# Generated by Django 4.2.5 on 2023-10-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_attribute_career_careerpath_class_race_skill_talent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='initiative',
            field=models.CharField(null=True),
        ),
    ]
