# Generated by Django 4.2.5 on 2023-10-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_itemother_qualities_and_flaws'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemother',
            name='qualities_and_flaws',
        ),
    ]
