# Generated by Django 4.2.5 on 2023-11-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_attribute_short_name_remove_career_career_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.attribute'),
        ),
    ]
