# Generated by Django 4.2.5 on 2023-11-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_skill_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpath',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='talents',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='trappings',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='skills',
            field=models.ManyToManyField(null=True, to='main.skill'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='talents',
            field=models.ManyToManyField(null=True, to='main.talent'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='trappings',
            field=models.ManyToManyField(null=True, to='main.item'),
        ),
    ]
