# Generated by Django 4.2.5 on 2023-11-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_careerpath_skills_remove_careerpath_talents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='career_path',
            field=models.ManyToManyField(to='main.careerpath'),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='skills',
            field=models.ManyToManyField(to='main.skill'),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='talents',
            field=models.ManyToManyField(to='main.talent'),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='trappings',
            field=models.ManyToManyField(to='main.item'),
        ),
    ]
