# Generated by Django 4.2.5 on 2023-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_careerpath_skills_careerpath_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpath',
            name='trappings',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='trappings',
            field=models.CharField(null=True),
        ),
    ]
