# Generated by Django 4.2.5 on 2023-11-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_careerpath_trappings_careerpath_trappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpath',
            name='talents',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='talents',
            field=models.CharField(null=True),
        ),
    ]
